    
author:
  email: erik.seglem@gmail.com
  homepage: https://github.com/eseglem
  name: Erik Seglem
description: WattBox Custom Component for Home Assistant.
files:
- custom_components/blueprint/__init__.py
- custom_components/blueprint/const.py
- custom_components/blueprint/sensor.py
- custom_components/blueprint/switch.py
keywords:
- wattbox
- homeassistant
- home-assistant
- custom-component
- python
license: MIT License
name: wattbox
type: component
