default_config:

wattbox:
  - host: !secret wattbox_ip
    name: wattbox
    scan_interval: 00:00:05
  - host: !secret wattbox_ip
    name: wattbox2
    scan_interval: 00:00:05

logger:
  default: error
  logs:
    custom_components.wattbox: debug

