default_config:

wattbox:
  # - host: !secret wattbox1_ip
  #   name: wattbox1
  #   scan_interval: 00:00:30
  #   username: !secret wattbox1_username
  #   password: !secret wattbox1_password
  - host: !secret wattbox2_ip
    name: wattbox2
    scan_interval: 00:00:30
    port: 22
    username: !secret wattbox2_username
    password: !secret wattbox2_password

logger:
  default: warning
  logs:
    custom_components.wattbox: debug
    pywattbox: debug
    # scrapli: debug
